# Конфигурация Cargo для ускорения сборки

[build]
# jobs параметр удалён: 0 приводил к ошибке 'jobs may not be 0'; без задания Cargo сам выберет количество потоков.
# jobs = 0  # (ранее) автоматическое определение числа ядер

# Настройки линкера для Windows
[target.'cfg(windows)']
rustflags = [
  # Более быстрый линкер lld (если установлен)
  "-C", "link-arg=-fuse-ld=lld",
  # Включить инкрементальное LTO
  "-C", "target-feature=+crt-static"
]

# Настройки кеширования
[net]
git-fetch-with-cli = true
offline = false

# Оптимизация для incremental compilation
[profile.dev]
incremental = true

[profile.dev-fast]
incremental = true